//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Dominio_Integra
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ModeloContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ModeloContainer usando la cadena de conexión encontrada en la sección 'ModeloContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public ModeloContainer() : base("name=ModeloContainer", "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloContainer.
        /// </summary>
        public ModeloContainer(string connectionString) : base(connectionString, "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ModeloContainer.
        /// </summary>
        public ModeloContainer(EntityConnection connection) : base(connection, "ModeloContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Producto> ProductoEstablecer
        {
            get
            {
                if ((_ProductoEstablecer == null))
                {
                    _ProductoEstablecer = base.CreateObjectSet<Producto>("ProductoEstablecer");
                }
                return _ProductoEstablecer;
            }
        }
        private ObjectSet<Producto> _ProductoEstablecer;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Servicio> ServicioEstablecer
        {
            get
            {
                if ((_ServicioEstablecer == null))
                {
                    _ServicioEstablecer = base.CreateObjectSet<Servicio>("ServicioEstablecer");
                }
                return _ServicioEstablecer;
            }
        }
        private ObjectSet<Servicio> _ServicioEstablecer;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ProductoEstablecer. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToProductoEstablecer(Producto producto)
        {
            base.AddObject("ProductoEstablecer", producto);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ServicioEstablecer. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToServicioEstablecer(Servicio servicio)
        {
            base.AddObject("ServicioEstablecer", servicio);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="Producto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Producto : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Producto.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="precio">Valor inicial de la propiedad precio.</param>
        /// <param name="descuento">Valor inicial de la propiedad descuento.</param>
        /// <param name="impuesto">Valor inicial de la propiedad impuesto.</param>
        /// <param name="descripcion_empaque">Valor inicial de la propiedad descripcion_empaque.</param>
        /// <param name="peso">Valor inicial de la propiedad peso.</param>
        /// <param name="color">Valor inicial de la propiedad color.</param>
        /// <param name="tamano">Valor inicial de la propiedad tamano.</param>
        /// <param name="oid">Valor inicial de la propiedad oid.</param>
        public static Producto CreateProducto(global::System.String id, global::System.String nombre, global::System.String descripcion, global::System.String precio, global::System.String descuento, global::System.String impuesto, global::System.String descripcion_empaque, global::System.String peso, global::System.String color, global::System.String tamano, global::System.Int32 oid)
        {
            Producto producto = new Producto();
            producto.id = id;
            producto.nombre = nombre;
            producto.descripcion = descripcion;
            producto.precio = precio;
            producto.descuento = descuento;
            producto.impuesto = impuesto;
            producto.descripcion_empaque = descripcion_empaque;
            producto.peso = peso;
            producto.color = color;
            producto.tamano = tamano;
            producto.oid = oid;
            return producto;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.String _precio;
        partial void OnprecioChanging(global::System.String value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descuento
        {
            get
            {
                return _descuento;
            }
            set
            {
                OndescuentoChanging(value);
                ReportPropertyChanging("descuento");
                _descuento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descuento");
                OndescuentoChanged();
            }
        }
        private global::System.String _descuento;
        partial void OndescuentoChanging(global::System.String value);
        partial void OndescuentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String impuesto
        {
            get
            {
                return _impuesto;
            }
            set
            {
                OnimpuestoChanging(value);
                ReportPropertyChanging("impuesto");
                _impuesto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("impuesto");
                OnimpuestoChanged();
            }
        }
        private global::System.String _impuesto;
        partial void OnimpuestoChanging(global::System.String value);
        partial void OnimpuestoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion_empaque
        {
            get
            {
                return _descripcion_empaque;
            }
            set
            {
                Ondescripcion_empaqueChanging(value);
                ReportPropertyChanging("descripcion_empaque");
                _descripcion_empaque = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion_empaque");
                Ondescripcion_empaqueChanged();
            }
        }
        private global::System.String _descripcion_empaque;
        partial void Ondescripcion_empaqueChanging(global::System.String value);
        partial void Ondescripcion_empaqueChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String peso
        {
            get
            {
                return _peso;
            }
            set
            {
                OnpesoChanging(value);
                ReportPropertyChanging("peso");
                _peso = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("peso");
                OnpesoChanged();
            }
        }
        private global::System.String _peso;
        partial void OnpesoChanging(global::System.String value);
        partial void OnpesoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String color
        {
            get
            {
                return _color;
            }
            set
            {
                OncolorChanging(value);
                ReportPropertyChanging("color");
                _color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("color");
                OncolorChanged();
            }
        }
        private global::System.String _color;
        partial void OncolorChanging(global::System.String value);
        partial void OncolorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tamano
        {
            get
            {
                return _tamano;
            }
            set
            {
                OntamanoChanging(value);
                ReportPropertyChanging("tamano");
                _tamano = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tamano");
                OntamanoChanged();
            }
        }
        private global::System.String _tamano;
        partial void OntamanoChanging(global::System.String value);
        partial void OntamanoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 oid
        {
            get
            {
                return _oid;
            }
            set
            {
                if (_oid != value)
                {
                    OnoidChanging(value);
                    ReportPropertyChanging("oid");
                    _oid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("oid");
                    OnoidChanged();
                }
            }
        }
        private global::System.Int32 _oid;
        partial void OnoidChanging(global::System.Int32 value);
        partial void OnoidChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Modelo", Name="Servicio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Servicio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Servicio.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="precio">Valor inicial de la propiedad precio.</param>
        /// <param name="descuento">Valor inicial de la propiedad descuento.</param>
        /// <param name="impuesto">Valor inicial de la propiedad impuesto.</param>
        /// <param name="oid">Valor inicial de la propiedad oid.</param>
        public static Servicio CreateServicio(global::System.String id, global::System.String nombre, global::System.String descripcion, global::System.String precio, global::System.String descuento, global::System.String impuesto, global::System.Int32 oid)
        {
            Servicio servicio = new Servicio();
            servicio.id = id;
            servicio.nombre = nombre;
            servicio.descripcion = descripcion;
            servicio.precio = precio;
            servicio.descuento = descuento;
            servicio.impuesto = impuesto;
            servicio.oid = oid;
            return servicio;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.String _precio;
        partial void OnprecioChanging(global::System.String value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descuento
        {
            get
            {
                return _descuento;
            }
            set
            {
                OndescuentoChanging(value);
                ReportPropertyChanging("descuento");
                _descuento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descuento");
                OndescuentoChanged();
            }
        }
        private global::System.String _descuento;
        partial void OndescuentoChanging(global::System.String value);
        partial void OndescuentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String impuesto
        {
            get
            {
                return _impuesto;
            }
            set
            {
                OnimpuestoChanging(value);
                ReportPropertyChanging("impuesto");
                _impuesto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("impuesto");
                OnimpuestoChanged();
            }
        }
        private global::System.String _impuesto;
        partial void OnimpuestoChanging(global::System.String value);
        partial void OnimpuestoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 oid
        {
            get
            {
                return _oid;
            }
            set
            {
                if (_oid != value)
                {
                    OnoidChanging(value);
                    ReportPropertyChanging("oid");
                    _oid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("oid");
                    OnoidChanged();
                }
            }
        }
        private global::System.Int32 _oid;
        partial void OnoidChanging(global::System.Int32 value);
        partial void OnoidChanged();

        #endregion
    
    }

    #endregion
    
}
